source "https://rubygems.org"
gem "activesupport"
gem "rb-appscript"
gem "autotask_api", github: 'scoop/autotask_api'
gem "github_api"
# gem "system_timer"
gem "ruby-trello"
gem "jira-ruby"
gem "leankitkanban"
gem "pry"
